# Generated by Django 5.0.3 on 2024-03-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tashxis',
            old_name='licheniya',
            new_name='lecheniya',
        ),
    ]
