# Generated by Django 5.0.3 on 2024-03-21 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0003_remove_bemor_created_at_remove_bemor_dad_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemor',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 7, 48, 48, 399126, tzinfo=datetime.timezone.utc)),
        ),
    ]
