# Generated by Django 5.0.3 on 2024-03-21 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0004_alter_bemor_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tashxis',
            name='tolov_qilingan_sana',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 8, 38, 52, 73507, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 8, 38, 52, 73507, tzinfo=datetime.timezone.utc)),
        ),
    ]
