# Generated by Django 5.0.3 on 2024-03-21 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0005_tashxis_tolov_qilingan_sana_alter_bemor_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tashxis',
            name='tolov_qilingan_sana',
        ),
        migrations.AlterField(
            model_name='bemor',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 8, 48, 52, 990449, tzinfo=datetime.timezone.utc)),
        ),
    ]
