# Generated by Django 5.0.3 on 2024-03-21 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0006_remove_tashxis_tolov_qilingan_sana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tashxis',
            name='tashxis',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bemor',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 12, 51, 40, 653255, tzinfo=datetime.timezone.utc)),
        ),
    ]
