# Generated by Django 5.0.3 on 2024-03-22 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0008_alter_bemor_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tashxis',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 3, 44, 2, 536999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 3, 44, 2, 535999, tzinfo=datetime.timezone.utc)),
        ),
    ]
