# Generated by Django 5.0.3 on 2024-03-22 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0010_alter_bemor_date_created_alter_tashxis_bemor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemor',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 6, 1, 26, 749439, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tashxis',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 6, 1, 26, 750440, tzinfo=datetime.timezone.utc)),
        ),
    ]
