# Generated by Django 5.0.3 on 2024-03-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klinika', '0012_remove_tashxis_bemor_delete_bemor_delete_tashxis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tashxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tashxis', models.CharField(max_length=100)),
                ('licheniya', models.CharField(max_length=100)),
                ('tolagan_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qolgan_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sana', models.DateField(auto_now_add=True)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.bemor')),
            ],
        ),
    ]
