# Generated by Django 5.0.3 on 2024-03-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashxis',
            name='bemor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bemor', to='klinika.bemor'),
        ),
    ]
