# Generated by Django 5.0.3 on 2024-03-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0014_alter_tashxis_bemor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tashxis',
            name='jami',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
    ]
