# Generated by Django 5.0.3 on 2024-03-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0015_tashxis_jami'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tashxis',
            old_name='jami',
            new_name='jami_narxi',
        ),
    ]
